### ISSUE TITLE
heartbeat thread does not stop on disconnect and results in exception when exiting

### ISSUE THREAD

**Issue by kuggenhoffen** [invisibleroads/socketIO-client#111]
Doing a disconnect and exiting program will result in following exception from heartbeat thread:

```
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.6.5-py2.7.egg/socketIO_client/heartbeats.py", line 27, in run
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.6.5-py2.7.egg/socketIO_client/__init__.py", line 192, in _ping
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.6.5-py2.7.egg/socketIO_client/transports.py", line 159, in send_packet
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
```

**Comment by invisibleroads** [comment]
Jaakko, thanks for reporting this issue. I added a fix but was not able to test it because the error is sporadic. Please tell us if it appears again.
