### ISSUE TITLE
IOError: [Errno socket error] [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by Santosh110892** [invisibleroads/socketIO-client#150]
santosh@santosh-desktop:~/First$ python $HOME/First/New3.py Traceback (most recent call last):   File "/home/santosh/First/New3.py", line 188, in <module>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)  
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   
File "/home/santosh/First/New3.py", line 169, in main     train()   File "/home/santosh/First/New3.py", line 26, in train     fake_data=FLAGS.fake_data)   
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 227, in read_data_sets     SOURCE_URL + TRAIN_IMAGES)   
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 208, in maybe_download     temp_file_name, _ = urlretrieve_with_retry(source_url)   
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 165, in wrapped_fn     return fn(*args, **kwargs)   
File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 190, in urlretrieve_with_retry     return urllib.request.urlretrieve(url, filename)   
File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve     return opener.retrieve(url, filename, reporthook, data)   File "/usr/lib/python2.7/urllib.py", line 245, in retrieve     fp = self.open(url, data)   File "/usr/lib/python2.7/urllib.py", line 213, in open     return getattr(self, name)(url)   
File "/usr/lib/python2.7/urllib.py", line 350, in open_http     h.endheaders(data)   
File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders     self._send_output(message_body)   
File "/usr/lib/python2.7/httplib.py", line 897, in _send_output     self.send(msg)   
File "/usr/lib/python2.7/httplib.py", line 859, in send     self.connect()   
File "/usr/lib/python2.7/httplib.py", line 836, in connect     self.timeout, self.source_address)   
File "/usr/lib/python2.7/socket.py", line 557, in create_connection     for res in getaddrinfo(host, port, 0, SOCK_STREAM): 
IOError: [Errno socket error] [Errno -3] Temporary failure in name resolution

Please help me sort out this prob.

**Comment by lijing666** [comment]
@Santosh110892 Have you already find the problems? I got this problem too. I am a beginner of tensorFlow. Thanks for your answer!
