### ISSUE TITLE
default installation is not working

### ISSUE THREAD

**Issue by santiago** [invisibleroads/socketIO-client#178]
great project! thanks.

can you fix it such that this works out of the box?

**Comment by flagstone78** [comment]
I am also having this problem. To be more specific this is my stack trace


DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:8124 "GET /socket.io/?EIO=3&transport=polling&t=1521356971113-0 HTTP/1.1" 200 104
Traceback (most recent call last):
  File "../../rpi_ws281x/python/examples/testled.py", line 19, in <module>
    io = SocketIO('localhost', 8124)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
StopIteration

UPDATE: I figured out why its not working. It is because i am using socket.io version 2 and you say right on the front page that you only support version 1. The way i worked around it was to pip install socketIO-client-nexus .
