### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by fr0stbytess** [invisibleroads/socketIO-client#180]
Hi guys,

so when I run the command "pip install -U socketIO-client" on CMD, here is what I get;

> C:\WINDOWS\system32>pip install -U socketIO-client
Collecting socketIO-client
  Using cached https://files.pythonhosted.org/packages/12/d4/abeb2596c2f16276c66910362b27d04b8d2cf12a746dcccf1d00de3f691b/socketIO-client-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\revaz\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "c:\users\revaz\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "c:\users\revaz\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\dist.py", line 16, in <module>
        import pkg_resources
      File "c:\users\revaz\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Revaz\AppData\Local\Temp\pip-install-pa2fkzge\socketIO-client\

**Comment by fr0stbytess** [comment]
nevermind, got this fixed

**Comment by ghanashyamvtatti** [comment]
Hello  @frostyworks 
I'm facing the same issue. It would really help if you could tell me how you fixed it.
Thank you.

**Comment by fr0stbytess** [comment]
@ghanashyamvtatti Have you tried `pip install python-socketio`?

**Comment by ghanashyamvtatti** [comment]
@frostyworks That worked. Thank you 😅

**Comment by Joshua-Swain** [comment]
Did you replace `socketIO-Client` with `python-socketio`, or is that something to be installed before?
Can this be done with `pip3`?
