### ISSUE TITLE
Crash in recv_packet

### ISSUE THREAD

**Issue by rabrahamkns** [invisibleroads/socketIO-client#207]
Hello,

I am running a socketio server on node, and separately I am running a python application wchich uses socketIO-client. 
After a while my python application crashes with this stack trace:

`stderr: Exception in thread Thread-2:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/app/analytics/src/transport/transport_socketio.py", line 41, in run
    self.parent and self.parent.dvz_socket_io.wait()  # disconnects, interrupts
  File "/usr/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 232, in wait
    self._process_packets()
  File "/usr/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 254, in _process_packets
    for engineIO_packet in self._transport.recv_packet():
  File "/usr/lib/python2.7/dist-packages/socketIO_client/transports.py", line 155, in recv_packet
    six.b(packet_text))
  File "/usr/lib/python2.7/dist-packages/socketIO_client/parsers.py", line 93, in parse_packet_text
    packet_type = int(get_character(packet_text, 0))
  File "/usr/lib/python2.7/dist-packages/socketIO_client/symmetries.py", line 17, in get_character
    return chr(get_byte(x, index))
  File "/usr/lib/python2.7/dist-packages/socketIO_client/symmetries.py", line 21, in get_byte
    return six.indexbytes(x, index)
  File "/usr/lib/python2.7/dist-packages/six.py", line 520, in indexbytes
    return ord(buf[i])
TypeError: 'NoneType' object has no attribute '__getitem__'`

My setup:
linux ubuntu trusty
node v  4.4.7
python 2.7.6
socketIO-client 0.7.2

Thanks
PS - this is a little different from issue #129 and #148 , although most of the stack is similar those issues have a 'string index out of range' here it is 'TypeError: NoneType object has no attribute __getitem__' which I think means the passed argument is None.
Also #129 and #148 starts from XHR_PollingTransport.revc_packet(), but this call stack starts from class WebsocketTransport.recv_packet()

Edit: this one is weird since it is saying that the packet_text variable from transports.py is None, however, it did manage to encode the payload.
From transports.py:

def recv_packet(self):
        try:
            packet_text = self._connection.recv()
       # ... some exception handling here
        if not isinstance(packet_text, six.binary_type):
            packet_text = packet_text.encode('utf-8') # this line did not crash
        engineIO_packet_type, engineIO_packet_data = parse_packet_text(
            packet_text) # this line crashes down the call stack since packet_text is None
        yield engineIO_packet_type, engineIO_packet_data

So the only thing I can think of is that the line:
packet_text = packet_text.encode('utf-8') 
returned None, which doesn't make sense to me.

**Comment by rabrahamkns** [comment]
I looked into the c source code of python's encode here it is:
`PyObject *PyString_Encode(const char *s,
                          Py_ssize_t size,
                          const char *encoding,
                          const char *errors)
{
    PyObject *v, *str;

    str = PyString_FromStringAndSize(s, size);
    if (str == NULL)
        return NULL;
    v = PyString_AsEncodedString(str, encoding, errors);
    Py_DECREF(str);
    return v;
}`

PyString_FromStringAndSize:
`/*
   For PyString_FromString(), the parameter `str' points to a null-terminated
   string containing exactly `size' bytes.

   For PyString_FromStringAndSize(), the parameter `str' is
   either NULL or else points to a string containing at least `size' bytes.
   For PyString_FromStringAndSize(), the string in the `str' parameter does
   not have to be null-terminated.  (Therefore it is safe to construct a
   substring by calling `PyString_FromStringAndSize(origstring, substrlen)'.)
   If `str' is NULL then PyString_FromStringAndSize() will allocate `size+1'
   bytes (setting the last byte to the null terminating character) and you can
   fill in the data yourself.  If `str' is non-NULL then the resulting
   PyString object must be treated as immutable and you must not fill in nor
   alter the data yourself, since the strings may be shared.

   The PyObject member `op->ob_size', which denotes the number of "extra
   items" in a variable-size object, will contain the number of bytes
   allocated for string data, not counting the null terminating character.
   It is therefore equal to the `size' parameter (for
   PyString_FromStringAndSize()) or the length of the string in the `str'
   parameter (for PyString_FromString()).
*/
PyObject *
PyString_FromStringAndSize(const char *str, Py_ssize_t size)
{
    register PyStringObject *op;
    if (size < 0) {
        PyErr_SetString(PyExc_SystemError,
            "Negative size passed to PyString_FromStringAndSize");
        return NULL;
    }
    if (size == 0 && (op = nullstring) != NULL) {
#ifdef COUNT_ALLOCS
        null_strings++;
#endif
        Py_INCREF(op);
        return (PyObject *)op;
    }
    if (size == 1 && str != NULL &&
        (op = characters[*str & UCHAR_MAX]) != NULL)
    {
#ifdef COUNT_ALLOCS
        one_strings++;
#endif
        Py_INCREF(op);
        return (PyObject *)op;
    }

    if (size > PY_SSIZE_T_MAX - PyStringObject_SIZE) {
        PyErr_SetString(PyExc_OverflowError, "string is too large");
        return NULL;
    }

    /* Inline PyObject_NewVar */
    op = (PyStringObject *)PyObject_MALLOC(PyStringObject_SIZE + size);
    if (op == NULL)
        return PyErr_NoMemory();
    (void)PyObject_INIT_VAR(op, &PyString_Type, size);
    op->ob_shash = -1;
    op->ob_sstate = SSTATE_NOT_INTERNED;
    if (str != NULL)
        Py_MEMCPY(op->ob_sval, str, size);
    op->ob_sval[size] = '\0';
    /* share short strings */
    if (size == 0) {
        PyObject *t = (PyObject *)op;
        PyString_InternInPlace(&t);
        op = (PyStringObject *)t;
        nullstring = op;
        Py_INCREF(op);
    } else if (size == 1 && str != NULL) {
        PyObject *t = (PyObject *)op;
        PyString_InternInPlace(&t);
        op = (PyStringObject *)t;
        characters[*str & UCHAR_MAX] = op;
        Py_INCREF(op);
    }
    return (PyObject *) op;
}`

So indeed there are cases where encode will return NULL. It is also possible that PyErr_SetString is called and sets the Unix errno variable, as described here:
https://docs.python.org/2/c-api/exceptions.html

Conclusion: it is possible for encode to return null. Will look into how to fix this.

**Comment by rabrahamkns** [comment]
Update: I now think that encode is returning null because some of the characters in the input may be invalid utf-8 characters (e.g. 0x80). I am going to fork this repo and attempt to handle it as a noop in case the encode returns null.

**Comment by rabrahamkns** [comment]
Here is my new recv_packet in transports.py (untested yet):

    def recv_packet(self):
        try:
            packet_text = self._connection.recv()
        except WebSocketTimeoutException as e:
            raise TimeoutError('recv timed out (%s)' % e)
        except SSLError as e:
            raise ConnectionError('recv disconnected by SSL (%s)' % e)
        except WebSocketConnectionClosedException as e:
            raise ConnectionError('recv disconnected (%s)' % e)
        except SocketError as e:
            raise ConnectionError('recv disconnected (%s)' % e)
        if not isinstance(packet_text, six.binary_type):
            packet_text = packet_text.encode('utf-8')
        # check if packet text is even defined, if not it will raise a NameError
        try:
            packet_text
        except NameError:
            sys.stderr.write('socketIO_client.transports.recv_packet() - packet_text is not defined')
            packet_text = None
        # if packet_text is None, either bacause encode returned NULL, or it was not defined
        # then send a noop
        if packet_text is None:
            sys.stderr.write('socketIO_client.transports.recv_packet() - packet_text is none, will handle a dummy "noop packet')
            engineIO_packet_type = 6
            engineIO_packet_data = ''
        else:
            engineIO_packet_type, engineIO_packet_data = parse_packet_text(packet_text)

        yield engineIO_packet_type, engineIO_packet_data

**Comment by rabrahamkns** [comment]
I made a mistake, this happened wthj socketio-client 0.6.5 which relies on websocket 0.12, where it seems this has been fixed in 0.7.2. CLosing this.
