### ISSUE TITLE
Unable to install socketIO-client module on docker 

### ISSUE THREAD

**Issue by svnsatyasai** [invisibleroads/socketIO-client#208]
Collecting socketIO-client==0.5.6
  Using cached https://files.pythonhosted.org/packages/6e/26/a9483358b9f266a21ae9bfe9012f168c58c1ba34f99dfab26e681bcc061e/socketIO-client-0.5.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3vudlhpo/socketIO-client/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3vudlhpo/socketIO-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3vudlhpo/socketIO-client/pip-egg-info
         cwd: /tmp/pip-install-3vudlhpo/socketIO-client/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3vudlhpo/socketIO-client/setup.py", line 6, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5786: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by svnsatyasai** [comment]
**System info -** 

docker image info - ubuntu 18.0.4
pip3 version - 19.3.1
python version - 3.6
