### ISSUE TITLE
0.5.6 fails to build due to invalid character in README.rst

### ISSUE THREAD

**Issue by tomh4x** [invisibleroads/socketIO-client#213]
```
Collecting socketio-client==0.5.6
  Downloading socketIO-client-0.5.6.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rd82duxw/socketio-client/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rd82duxw/socketio-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3x1qteoz
         cwd: /tmp/pip-install-rd82duxw/socketio-client/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rd82duxw/socketio-client/setup.py", line 6, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5786: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

https://github.com/invisibleroads/socketIO-client/commit/a42704e0ab629d21d5d62f96861048d7c3711004 line 159:

`Jörgen`

**Comment by tomh4x** [comment]
Related:

https://github.com/MISP/misp-docker/issues/91

**Comment by tomh4x** [comment]
```
>>> b'\xc3\xb6'.decode('ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
>>> b'\xc3\xb6'.decode('utf-8')
'ö'
>>>

```
