### ISSUE TITLE
Cannot import name SocketIO

### ISSUE THREAD

**Issue by caioketo** [invisibleroads/socketIO-client#49]
I was trying to use socketIO_client but always getting this error:

"from socketIO_client import SocketIO
ImportError: cannot import name SocketIO"

**Comment by claus25** [comment]
hello 
please I almost have the same problem and I try this solution but nothing.
perable program or batch file.
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from config import config
  File "C:\Users\lenovo\Desktop\RGBD_Semantic_Segmentation_PyTorch-master\model\SA-Gate.nyu.432\config.py", line 58, in <module>
    from furnace.utils.pyt_utils import model_urls
  File "C:\Users\lenovo\miniconda3\lib\site-packages\furnace\__init__.py", line 20, in <module>
    from .context import ContainerContext  # NOQA: F401 '.context.ContainerContext' imported but unused
  File "C:\Users\lenovo\miniconda3\lib\site-packages\furnace\context.py", line 28, in <module>
    from . import pid1
  File "C:\Users\lenovo\miniconda3\lib\site-packages\furnace\pid1.py", line 27, in <module>
    from socket import sethostname
ImportError: cannot import name 'sethostname' from 'socket' (C:\Users\lenovo\miniconda3\lib\socket.py)

please help me
