### ISSUE TITLE
How to use/install on Win8?

### ISSUE THREAD

**Issue by AlexanderVielhauer** [invisibleroads/socketIO-client#97]
Hello,

how do I execute the install instructions (https://pypi.python.org/pypi/socketIO-client) correctly on my Windows machine? Or is "py -m pip install -U socketIO-client" okay as well?

When I try "s = socketIO('localhost', 8094)" with a server listening on port 8094, it gives me an error:

C:\Users\Alexander\Desktop\helpstone\streamerApp>py streamerApp.py
Traceback (most recent call last):
  File "streamerApp.py", line 775, in <module>
    main()
  File "streamerApp.py", line 745, in main
    s = SocketIO('localhost', 8094)
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python35\lib\site-packa
ges\socketIO_client\__init__.py", line 331, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python35\lib\site-packa
ges\socketIO_client\__init__.py", line 51, in __init__
    self._transport
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python35\lib\site-packa
ges\socketIO_client\__init__.py", line 59, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "C:\Users\Alexander\AppData\Local\Programs\Python\Python35\lib\site-packa
ges\socketIO_client\__init__.py", line 73, in _get_engineIO_session
    transport.recv_packet())
StopIteration

**Comment by invisibleroads** [comment]
We haven't tested the library on Windows yet.

Does the script work in Linux? If it works, then it might be a Windows-specific issue.

**Comment by Tutorgaming** [comment]
From the ubuntu 16.04 user, I've also got the same problem.

**Comment by aaryadev** [comment]
Same on ubuntu 16.4 raspi2  and raspi 3
